#!/usr/bin/env python

import argparse
import datetime
from importlib import import_module
from pathlib import Path
import shutil
import subprocess
import sys

DOCS_DIR = Path(sys.argv[0]).absolute().parent
MODULES_DIR = DOCS_DIR.parent

def remove_dir(dirpath):
    if dirpath.exists() and dirpath.is_dir():
        shutil.rmtree(dirpath)

def build_module_docs():
    v = ["0", "12", "3"]
    mod_docs = MODULES_DIR / "docs"
    mod_build = mod_docs / "build"
    conf_copy = mod_docs / "conf.py"
    logo_copy = mod_docs / "CQCLogo.png"
    shutil.copy(DOCS_DIR / "conf.py", conf_copy)
    shutil.copy(DOCS_DIR / "CQCLogo.png", logo_copy)
    remove_dir(mod_build)
    index_rst = mod_docs / "index.rst"

    subprocess.run(
        [
            "sphinx-build",
            "-b",
            "html",
            "-D",
            f"project=qujax",
            "-D",
            f"copyright={datetime.date.today().year} Cambridge Quantum Computing",
            "-D",
            f"version={'.'.join(v[:2])}",
            "-D",
            f"release={'.'.join(v)}",
            ".",
            "build",
        ],
        cwd=mod_docs,
    )
    conf_copy.unlink()
    logo_copy.unlink()
    index_rst.unlink()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Build HTML documentation for qujax."
    )
    parser.add_argument("-d", "--dest", help="copy artifacts into destination folder")
    args = parser.parse_args()

    build_module_docs()

    if args.dest is not None:
        dest = Path(args.dest)
        shutil.copytree(
            MODULES_DIR / "docs" / "build",
            dest,
            dirs_exist_ok=True,
            )
